/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkIndexRouteImport } from './routes/work/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as LogIndexRouteImport } from './routes/log/index'
import { Route as CvIndexRouteImport } from './routes/cv/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogIndexRoute = LogIndexRouteImport.update({
  id: '/log/',
  path: '/log/',
  getParentRoute: () => rootRouteImport,
} as any)
const CvIndexRoute = CvIndexRouteImport.update({
  id: '/cv/',
  path: '/cv/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cv/': typeof CvIndexRoute
  '/log/': typeof LogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cv': typeof CvIndexRoute
  '/log': typeof LogIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cv/': typeof CvIndexRoute
  '/log/': typeof LogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cv/' | '/log/' | '/projects/' | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cv' | '/log' | '/projects' | '/work'
  id: '__root__' | '/' | '/cv/' | '/log/' | '/projects/' | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CvIndexRoute: typeof CvIndexRoute
  LogIndexRoute: typeof LogIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log/': {
      id: '/log/'
      path: '/log'
      fullPath: '/log/'
      preLoaderRoute: typeof LogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv/': {
      id: '/cv/'
      path: '/cv'
      fullPath: '/cv/'
      preLoaderRoute: typeof CvIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CvIndexRoute: CvIndexRoute,
  LogIndexRoute: LogIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
